### ISSUE TITLE
Internet Explorer

### ISSUE THREAD

**Issue by apuyou** [simde-utc/portail-old#10]
Oui, Internet Explorer c'est le mal, tout ça, ok...

Mais sous IE7, on ne peut même pas se connecter (menu déroulant inopérant) et plein de boutons sont décalés donc inaccessibles.

Le site devrait au moins avoir l'air présentable quand on arrive sur la page d'accueil !

**Comment by apuyou** [comment]
Bon ok IE7 c'est moins de 3%, mais je suis pas sur que ce soit beaucoup mieux avec IE8/9 (et les trois ensemble sont dans les 20% de PDM).

Source : http://stats.wikimedia.org/archive/squid_reports/2012-10/SquidReportClients.htm

**Comment by MiLk** [comment]
Pas de soucis particulier sous IE9 64bits sous Win7

**Comment by apuyou** [comment]
#21 va grandement améliorer les choses

**Comment by apuyou** [comment]
#21 closed
