### ISSUE TITLE
Faciliter la saisie des dates pour les évenements

### ISSUE THREAD

**Issue by mdamien** [simde-utc/portail-old#129]
Bonjour, la saisie des dates pour les évenement est un peu galére, beaucoup de dropdown.

Je propose de soit:
- Pré-remplir les dropdown (avec la date du jour courant par exemple)
- Pré-remplir la "fin de l'évenement" avec la date du début (comme ca j'ai juste à modifier l'heure par exemple
- Plus radicalement, utiliser un widget JQuery UI DatePicker plutot que des dropdown (choix contestable, je sais)

**Comment by mattgu74** [comment]
Ou alors utiliser le champ html5

`<input type="date" >`
http://www.w3.org/TR/html-markup/input.date.html

A partir du moment ou les navigateurs sont compatibles, il y aura un date picker et en plus il sera adapté en fonction de la plateforme (genre sur un téléphone à mon avis ce ne sera pas comme sur un ordi...)

**Comment by mdamien** [comment]
Ouep, trés bonne remarque!

Le 20 novembre 2013 04:29, Matthieu Guffroy notifications@github.com a
écrit :

**Comment by MiLk** [comment]
Fait avec #131
