### ISSUE TITLE
Bug affichage sur carnet avantage

### ISSUE THREAD

**Issue by renanlecaro** [simde-utc/portail-old#147]
Bonjour

C'est juste moi qui ai ca ? 
![bug affichage carnet avantage](https://f.cloud.github.com/assets/3457214/2237732/bd84522e-9bc1-11e3-97e0-2c1fe0230008.png)
Chromium sur linuxmint

**Comment by apuyou** [comment]
Non, c'est partout :dancer: 

Il y a eu des corrections de bugs sur cette page qui passeront à la prochaine mise en prod (ce week-end), mais je sais plus si celui-ci est corrigé.
