### ISSUE TITLE
Upload de photos : Erreur 500

### ISSUE THREAD

**Issue by renanlecaro** [simde-utc/portail-old#149]
![portail bug upload](https://f.cloud.github.com/assets/3457214/2320184/52b0d370-a38a-11e3-8b57-e0328577adca.png)
Reponse du serveur suite a l'upload d'une photo : erreur 500
@arribbar tu peux jeter un oeil ?

**Comment by apuyou** [comment]
@Zicouto Tu dois pouvoir trouver des logs d'erreurs sur le serveur. Je verrais bien un souci de droit (il faut que les dossiers dans lesquels on upload appartiennent à l'utilisateur qui fait tourner le portail).

**Comment by brcorentin** [comment]
Bon je me suis plongé dans les logs.
Apparemment il essaierai d'upload dans un dossier qui n'existe pas.
@renanlecaro Tu pourrais me dire quel jour et vers quelle heure c'est arrivé? (comme ça je serais sur de lire les bon logs)

**Comment by renanlecaro** [comment]
Aujourd'hui 12h26 ;) (je viens de refaire un test)

**Comment by brcorentin** [comment]
J'ai moi aussi fais un test. Après avoir regarder tous les logs nginx et php, il n'y en a aucun qui parle de cette erreur. Il ne s'agit apparemment pas d'une erreur 500. Il faut que je regarde le dossier dans lequel les images sont upload que le problème ne vienne pas de là.

**Comment by brcorentin** [comment]
Problème réglé.
Les droits était bien réglé sur le dossier galeries mais le owner était root j'ai donc effectué un
$ chown -R www-data galeries et maintenant ça marche.
