### ISSUE TITLE
Problème quand on accède au profil d'un autre membre.

### ISSUE THREAD

**Issue by brcorentin** [simde-utc/portail-old#152]
Quand on accède au profil d'une autre personne sur le portail la photo qui s'affiche est la notre et pas celle du profil recherché.

**Comment by MiLk** [comment]
https://github.com/simde-utc/portail/blob/master/apps/frontend/modules/profile/templates/showSuccess.php#L13
`$sf_user->getGuardUser()->getUsername()` >> `$user->getUsername()`

**Comment by brcorentin** [comment]
Je voulais laisser cette issue pour faire travailler les nouveaux.
Mais bon pas grave je ferai la modif asap.
