### ISSUE TITLE
Ajouter un bouton "j'aime"

### ISSUE THREAD

**Issue by mattgu74** [simde-utc/portail-old#6]
Ajouter un bouton j'aime, sur les assos et les articles ;)

**Comment by mattgu74** [comment]
Ce serait vraiment cool sur les assos, pour pouvoir distinguer les "membres" des simples suiveurs de l'assos... (ex skiutc : y'a un paquet de membres, alors que certain ne font pas partie à proprement parlé de l'assos)

**Comment by apuyou** [comment]
C'est déjà implémenté dans la partie sociale ça il me semble, non ?

Arthur Puyou

2013/2/10 Matthieu Guffroy notifications@github.com

**Comment by mattgu74** [comment]
Je n'ai encore jamais vu cette partie ^^

**Comment by apuyou** [comment]
C'est sorti dans #55, on peut maintenant suivre une association.
