### ISSUE TITLE
Weekmail: Ajouter date et amphi à l'annonce dans le weekmail

### ISSUE THREAD

**Issue by mdamien** [simde-utc/portail-old#84]
L'annonce du weekmail ne comprenait pas l'amphi ni la date...c'est problématique ^^

**Comment by apuyou** [comment]
Tu veux dire qu'il faut ajouter la date et le lieu des événements dans le weekmail ?

**Comment by mdamien** [comment]
Yep, dans le weekmail, il y a juste le texte de l'annonce, il manque la date, le lieu, voir le site de l'asso par exemple.
