### ISSUE TITLE
[fix] Mettre a jour le local du BDE

### ISSUE THREAD

**Issue by mattgu74** [simde-utc/portail-old#9]
Le local du BDE n'est plus C118 depuis plus d'un semestre maintenant... Ce serait bien de mettre le portail à jour.

**Comment by apuyou** [comment]
Déjà demandé par le BDE. C'est à eux de mettre à jour leur profil.

**Comment by mattgu74** [comment]
Ok je leur envoie un mail pour leur dire de montrer l'exemple et mettre à jour leur profil !! Tabernacle ;)
